name: Build and Release Browser Assets

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_STAGING }}
      S3_ACCESS: ${{ secrets.AWS_S3_ACCESS }}
      S3_KEY: ${{ secrets.AWS_S3_KEY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build  # Ensure this builds your project appropriately for browser agents

    - name: List files in dist folder
      run: ls -l dist

    # - name: Make a zip of the dist folder
    #   run: zip -r dist.zip dist/

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_S3_SECRET }}
        aws-region: us-east-1
    - name: Copy files to the CDN with the AWS CLI
      run: |
        aws s3 cp dist/newrelic-video-dash.min.js s3://nr-downloads-main/media-agents/browser/videojs/
