name: Build and Generate Assets

on:
  push:
    tags:
      - 'v*.*.*' # Triggers on version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Archive build files
      run: |
        if [ -d "dist" ]; then
          zip -r dist.zip dist/
        else
          echo "No dist folder found"; exit 1
        fi

    - name: Check for existing release
      id: check_release
      uses: actions/github-script@v4
      with:
        script: |
          const { github, context } = require('@actions/github');
          try {
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: context.ref.replace('refs/tags/', ''),
            });
            return {
              exists: true,
              id: release.data.id,
            };
          } catch (error) {
            if (error.status === 404) {
              return { exists: false };
            }
            throw error;
          }

    - name: Publish GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        prerelease: true
        files: dist.zip
        discussion_category_name: Releases